title: default-project-template
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Step 1
  - title: Step 2
    completion:
      - engaged
  - title: Step 3
  - title: Step 4
  - title: Step 5
  - title: Step 6
  - title: Step 7
  - title: Step 8
  - title: Step 9
  - title: Step 10
  - title: Step 11
  - title: Step 12
    completion:
      - internal
  - title: Step 13
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Step 14
    completion:
      - external
