title: Target practice
hero_image: images/banner.png
description: Use Python to draw a target and score points by hitting it with arrows
meta_title: Python coding projects for kids and teens | Target practice
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Use Python to draw a target and score points by hitting it with arrows.
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
landing: true
steps:
  - title: Create a background
  - title: Draw the grass
    completion:
      - engaged
  - title: Draw a stand
  - title: Add a target circle
  - title: Finish the target
  - title: Add an arrow
  - title: Make the arrow move
  - title: Get the colour
  - title: Detect mouse clicks
  - title: Scoring points
  - title: More points
    completion:
      - internal
  - title: Missing the target
    completion:
      - external
